---
id: debian-gum-2012
tags:
- rabbit
- debian
base_name: rabbit
presentation_date: 2012/06/23
version: 2012.06.23.4
licenses:
- "GPLv3+"
- "Ruby's or GPLv2+"
- "Debian Open Use Logo License"
slideshare_id: rabbit-14073776
speaker_deck_id: rabbit-rabbit-debian
author:
  name: Kouhei Sutou
  email: kou@cozmixng.org
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
